---
- name: install nginx on ec2
  hosts: "{{ host }}"
  become: yes
  gather_facts: False
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx on Debian
      apt:
        name: nginx
        state: present
