---
- name: Launch EC2 Instance
  hosts: localhost
  gather_facts: False
  vars: 
    region: us-east-2  # Ohio
    ami: ami-0e83be366243f524a  
    key_name: ansible-key-ohio
    
  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
          name: "Ansible-VM-1"
          region: "{{ region }}"
          key_name: "{{ key_name }}"
          vpc_subnet_id: subnet-0c4a7e4cd8bb3b540
          instance_type: t2.micro
          security_group: sg-05dad18f2e7b0e9b3
          network:
            assign_public_ip: true
          image_id: "{{ ami }}"
          tags:
            Environment: Testing-Ansible

