---
- name: Launch EC2 Instance
  hosts: localhost
  gather_facts: False
  vars: 
    region: ap-south-1  # Mumbai region code
    instance_type: t2.micro
    ami: ami-0287a05f0ef0e9d9a  # Ubuntu AMI ID (replace with the latest Ubuntu AMI ID for the specified region)
    key_name: ansible-key  # Replace with your EC2 key pair name
    
  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
          name: "Ansible-VM"
          region: "{{ region }}"
          key_name: "ansible-key"
          vpc_subnet_id: subnet-0433a9f292a716070
          instance_type: t2.micro
          security_group: default
          network:
            assign_public_ip: true
          image_id: "{{ ami }}"
          tags:
            Environment: Testing

